name: Deploy Frontend & Rules to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # ✅ Authenticate Firebase using the Service Account
      - name: Authenticate Firebase CLI
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFINITY_MERCENARIES }}' > "$HOME/firebase-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      # ✅ Install and Build Frontend
      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # ✅ Deploy Firestore Rules
      - name: Deploy Firestore Rules
        run: |
          echo "Deploying Firestore Rules..."
          firebase deploy --only firestore:rules

      # ✅ Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFINITY_MERCENARIES }}
          channelId: live
          projectId: infinity-mercenaries
