# Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js 18 with OpenSSL compatibility
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use Node.js 18 for Firebase compatibility

      # Add OpenSSL Legacy Provider to fix Webpack build errors
      - name: Set OpenSSL Legacy Provider
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      # Install dependencies and build the frontend project
      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFINITY_MERCENARIES }}
          channelId: live
          projectId: infinity-mercenaries
