# Deploy to Firebase Hosting & Functions on merge to main
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js 18 for Firebase compatibility
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      # ✅ Authenticate Firebase CLI using Service Account Key
      - name: Authenticate Firebase CLI
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > "$HOME/firebase-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase auth:login --token "$(cat $HOME/firebase-key.json)"

      # ✅ Check Authentication Status (Debugging Step)
      - name: Check Authentication
        run: |
          firebase projects:list

      # Install and Build Frontend
      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend/functions
          npm ci

      # ✅ Deploy Firebase Hosting
      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFINITY_MERCENARIES }}
          channelId: live
          projectId: infinity-mercenaries

      # ✅ Fix: Deploy Firebase Functions with Service Account Authentication
      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "$HOME/firebase-key.json"
        run: |
          firebase deploy --only functions
