on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js 18 for Firebase compatibility
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Add OpenSSL Legacy Provider to fix Webpack build errors
      - name: Set OpenSSL Legacy Provider
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      # Install and Build Frontend
      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend/functions
          npm ci

      # Deploy to Firebase Hosting & Functions
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INFINITY_MERCENARIES }}
          channelId: live
          projectId: infinity-mercenaries

      # ✅ Fix: Deploy Firebase Functions (Backend)
      - name: Deploy Firebase Functions
        run: |
          firebase deploy --only functions
